# Site settings
title: 2145 | 2018-2145
description: '2145之正傳，記敘了人類到了2145年所面臨的關鍵抉擇。'
keywords: '科幻小説，阿甘科幻小説，2145'
url: 'https://je-pense.github.io/2145/'
author:
  name: '阿甘'
  email: 'winwinsfu@gmail.com'
  url: 'https://je-pense.github.io/2145/'

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: '1.0'

# Options
custom_header: false
custom_nav_footer: false
reverse: false
